name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag andreireinus/pdf-generator:$(date +%s)
  
    - name: Build & Push to Docker Hub
      uses: opspresso/action-docker@master
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: "andreireinus/pdf-generator"
        LATEST: "false"